name: Cache Substack RSS (mirror)
on:
  schedule:
    - cron: "17 7 * * *"
  workflow_dispatch: {}

permissions:
  contents: write

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Fetch from CORS-friendly mirror
        run: |
          set -e
          curl -L --fail --retry 5 --retry-all-errors --connect-timeout 15 --max-time 120 \
               "https://r.jina.ai/http://cloudandcapital.substack.com/feed" -o substack.xml

      - name: Commit changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add substack.xml
          git commit -m "chore: update Substack RSS via mirror" || echo "No changes to commit"
          git push
